export type SplitTagSnapshot = {
 tag: { tagId:string; materialCode:string; partName:string; customer:string; location:string; jobNo:string; productionDate:string; remainingQty:number; status:string };
 pick: { id:number; dueLineId:number; pickedQty:number; dispatchedQty:number; status:string; deliveryDate:string; deliveryTime:string; fact:string; doNo:string } | null;
 availableQty:number; waitingQty:number; loadedAt:string;
};
export type SplitLabelKind = 'delivery' | 'remaining';
export type SplitTagLabel = { kind:SplitLabelKind; qty:number; sourceTagId:string; materialCode:string; jobNo:string; productionDate:string; partName:string; customer:string; location:string; pickId:number|null; dueDate:string; dueTime:string; fact:string; doNo:string };
export function createSplitLabels(snapshot:SplitTagSnapshot,kinds:SplitLabelKind[]):SplitTagLabel[] {
 if(!kinds.length || kinds.some(kind=>!['delivery','remaining'].includes(kind)))throw new Error('กรุณาเลือกประเภท Tag ที่ต้องการพิมพ์');
 return [...new Set(kinds)].map(kind=>{
  const qty=kind==='delivery'?snapshot.waitingQty:snapshot.availableQty;
  if(kind==='delivery' && !snapshot.pick)throw new Error('ไม่พบรายการจัดงานสำหรับ Tag ส่งพร้อมงาน');
  if(!Number.isSafeInteger(qty)||qty<=0)throw new Error(kind==='delivery'?'ไม่มีงานรอส่งเหลือสำหรับพิมพ์ Tag':'ไม่มี Stock พร้อมใช้เหลือสำหรับพิมพ์ Tag คงเหลือ');
  return {kind,qty,sourceTagId:snapshot.tag.tagId,materialCode:snapshot.tag.materialCode,jobNo:snapshot.tag.jobNo,productionDate:snapshot.tag.productionDate,partName:snapshot.tag.partName,customer:snapshot.tag.customer,location:snapshot.tag.location,pickId:kind==='delivery'?snapshot.pick!.id:null,dueDate:kind==='delivery'?snapshot.pick!.deliveryDate:'',dueTime:kind==='delivery'?snapshot.pick!.deliveryTime:'',fact:kind==='delivery'?snapshot.pick!.fact:'',doNo:kind==='delivery'?snapshot.pick!.doNo:''};
 });
}
export function splitLabelPayload(label:SplitTagLabel,labelId:string,baseUrl:string) {
 // The remainder keeps the existing stock tag identity. The delivery QR traces a label;
 // it is intentionally not accepted as a receipt or a customer dispatch tag.
 if(label.kind==='remaining')return label.sourceTagId;
 const url=new URL(baseUrl);url.search='';url.hash='';url.searchParams.set('page','arrange');url.searchParams.set('splitLabel',labelId);return url.toString();
}
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderSplitLabels(labels:SplitTagLabel[],labelId:string,issuedAt:string,qrs:string[],paper:'a4'|'62mm') {
 if(labels.length!==qrs.length)throw new Error('ข้อมูล QR ไม่ครบ');
 const issuedTime=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(issuedAt));
 const cards=labels.map((label,i)=>`<section class="tag"><header><b>KiT</b><span>${label.kind==='delivery'?'TAG ส่งพร้อมงาน':'TAG คงเหลือใน Stock'}</span></header><div class="part"><small>PART NO.</small><strong>${escape(label.materialCode)}</strong><p>${escape(label.partName)}</p></div><div class="quantity"><b>${label.qty.toLocaleString('en-US')}</b><span>ชิ้น / PCS</span></div><div class="info"><div><small>JOB</small><b>${escape(label.jobNo)}</b></div><div><small>ผลิตวันที่</small><b>${escape(label.productionDate)}</b></div><div><small>ลูกค้า / Location</small><b>${escape(label.customer)} / ${escape(label.location)}</b></div>${label.kind==='delivery'?`<div><small>วันที่ส่ง / รอบ / FAC</small><b>${escape(label.dueDate)} ${escape(label.dueTime)} / ${escape(label.fact)}</b></div><div><small>DO / รายการจัดงาน</small><b>${escape(label.doNo)} / ${label.pickId}</b></div>`:''}<div class="source"><small>อ้างอิง Tag เดิม</small><b>${escape(label.sourceTagId)}</b></div></div><footer><img src="${escape(qrs[i])}" alt="QR"><div><b>${label.kind==='delivery'?'สแกนเพื่อตรวจสอบที่มา':'ใช้ QR นี้แทนฉลากเดิมบนกล่องคงเหลือ'}</b><p>${label.kind==='delivery'?'แนบกับงานที่จัด · ขายออกด้วย Tag ลูกค้าตามเดิม':'อ้างอิง Stock เดิม · ไม่ใช่การรับเข้าเพิ่ม'}</p><small>${escape(labelId)}<br>${escape(issuedTime)}</small></div></footer></section>`).join('');
 return `<!doctype html><html lang="th"><head><meta charset="utf-8"><title>KIT Tag แบ่งงาน</title><style>@page{size:${paper==='62mm'?'62mm 100mm':'A4 portrait'};margin:${paper==='62mm'?'0':'8mm'}}*{box-sizing:border-box}body{margin:0;font:12px Arial,sans-serif;color:#111;background:#fff}.toolbar{padding:16px;background:#eef5ff}button{padding:12px 20px;cursor:pointer}.sheet{display:grid;grid-template-columns:${paper==='62mm'?'1fr':'repeat(2,1fr)'};gap:${paper==='62mm'?'0':'5mm'};${paper==='62mm'?'width:62mm;':''}}.tag{border:1px solid #222;padding:${paper==='62mm'?'3mm':'4mm'};break-inside:avoid;${paper==='62mm'?'width:62mm;height:100mm;break-after:page;':'min-height:110mm;'}}header{display:flex;justify-content:space-between;gap:8px;border-bottom:2px solid #111;padding-bottom:5px;font-weight:bold}header>b{font-size:22px}.part{margin-top:8px}.part small,.info small{display:block;color:#444;font-size:${paper==='62mm'?'8':'10'}px}.part strong{display:block;font-size:${paper==='62mm'?'14':'18'}px;overflow-wrap:anywhere}.part p{margin:3px 0;font-size:${paper==='62mm'?'9':'11'}px}.quantity{text-align:center;border:2px solid #111;margin:6px 0;padding:3px}.quantity b{font-size:${paper==='62mm'?'32':'42'}px;display:block}.quantity span{font-size:11px}.info{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:4px;font-size:${paper==='62mm'?'9':'12'}px}.info b{overflow-wrap:anywhere}.info .source{grid-column:1/-1}.part p{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}footer{display:flex;gap:6px;align-items:center;margin-top:6px;border-top:1px solid #aaa;padding-top:5px;font-size:${paper==='62mm'?'8':'10'}px}footer img{width:${paper==='62mm'?'24':'30'}mm;height:${paper==='62mm'?'24':'30'}mm}footer p{margin:4px 0}footer small{display:block;overflow-wrap:anywhere;font-size:${paper==='62mm'?'6':'8'}px}@media print{.toolbar{display:none}.tag:last-child{break-after:auto}}</style></head><body><div class="toolbar"><button onclick="window.print()">พิมพ์ Tag</button><p>ตรวจจำนวนกับงานจริงก่อนแนบ Tag · เลือกกระดาษ ${paper==='62mm'?'62 × 100 mm':'A4'} และสเกล 100%</p></div><main class="sheet">${cards}</main></body></html>`;
}
