"use client";

/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef, useState } from "react";

import { reportOperationWarning } from "./operation-warning";
import { OverviewIcon } from "./stock-overview-icons";
import { stockStatus, type StockOverviewRow } from "./stock-quantities";

const fmt = (value: number) => Number(value || 0).toLocaleString("th-TH");
const dateLabel = (value: string) => value ? value.slice(0,10).split("-").reverse().join("/") : "—";

export function createOverviewWorkbook(xlsx: typeof import('xlsx'), rows: StockOverviewRow[], loadedAt: string) {
 const sheet=xlsx.utils.aoa_to_sheet([
  ['KIT · Stock ทั้งหมด','ข้อมูลล่าสุด',timeLabel(loadedAt)],
  ['คงเหลือรวม = Stock พร้อมใช้ + จัดงานรอส่ง · ตาม Search / Filter ปัจจุบัน'],
  ['Part No.','Description','Customer','Location','Stock Available','Arranged','Total Remaining','Active Tag Count','Status'],
  ...rows.map((r)=>[r.materialCode,r.partName,r.customer,r.location,r.availableQty,r.arrangedQty,r.totalQty,r.tagCount,stockStatus(r)]),
 ]);
 sheet['!cols']=[25,38,24,22,20,20,20,22,20].map(wch=>({wch}));sheet['!autofilter']={ref:`A3:I${rows.length+3}`};
 const book=xlsx.utils.book_new();xlsx.utils.book_append_sheet(book,sheet,'Stock ทุก Part');return book;
}
function timeLabel(value:string) { return value ? new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}$/.test(value) ? value.replace(' ','T')+'Z' : value)).replace(',','') : '—'; }
type Filters={search:string;status:string;customer:string;location:string;job:string;partGroup:string;availableOnly:boolean};
const EMPTY:Filters={search:'',status:'all',customer:'',location:'',job:'',partGroup:'',availableOnly:false};
export function stockFilterParams(f:Filters) {
 const p=new URLSearchParams();for(const key of ['search','status','customer','location','job','partGroup'] as const) if(f[key] && f[key]!=='all') p.set(key,f[key]);if(f.availableOnly)p.set('availableOnly','1');return p;
}
type Snapshot={rows:StockOverviewRow[];total:number;page:number;pageSize:number;loadedAt:string;summary:{partCount:number;availableQty:number;arrangedQty:number;totalQty:number};options:{customer:string;location:string;partGroup:string}[]};
type DetailRow={id?:string;tagId?:string;jobNo:string;qty?:number;receivedQty?:number;remainingQty?:number;availableQty?:number;arrangedQty?:number;productionDate?:string;receivedAt?:string;status?:string;location?:string;action?:string;occurredAt?:string;actor?:string};
type Detail={part:StockOverviewRow;rows:DetailRow[];total:number;page:number;pageSize:number};
const INITIAL:Snapshot={rows:[],total:0,page:1,pageSize:10,loadedAt:'',summary:{partCount:0,availableQty:0,arrangedQty:0,totalQty:0},options:[]};
function Photo({row}:{row:StockOverviewRow}) {const [failed,setFailed]=useState(false);return row.imageVersion && !failed ? <img className="stock-overview-photo" src={`/api/part-images?materialCode=${encodeURIComponent(row.materialCode)}&v=${encodeURIComponent(row.imageVersion)}`} alt={`รูป ${row.materialCode}`} loading="lazy" onError={()=>setFailed(true)}/> : <span className="stock-overview-photo placeholder" aria-hidden="true">◇</span>;}
function Badge({row}:{row:StockOverviewRow}) {return <span className={`stock-overview-badge ${row.totalQty<0?'negative':row.availableQty>0?'ready':row.arrangedQty>0?'arranged':'zero'}`}>{stockStatus(row)}</span>;}
export default function StockAllPage({canDetails,canExport}:{canDetails:boolean;canExport:boolean}) {
 const [filters,setFilters]=useState<Filters>(EMPTY),[data,setData]=useState<Snapshot>(INITIAL),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[refresh,setRefresh]=useState(0);
 const [loading,setLoading]=useState(true),[exporting,setExporting]=useState(false),[error,setErrorState]=useState(''),[showFilters,setShowFilters]=useState(true);
 const [checked,setChecked]=useState<string[]>([]);
 const [selected,setSelected]=useState(''),[tab,setTab]=useState('tag'),[detailPage,setDetailPage]=useState(1),[detail,setDetail]=useState<Detail|null>(null),[detailLoading,setDetailLoading]=useState(false),[detailError,setDetailErrorState]=useState('');
 const setError=(value:string)=>{setErrorState(value);if(value)reportOperationWarning({page:'stock-all',message:value});};
 const setDetailError=(value:string)=>{setDetailErrorState(value);if(value)reportOperationWarning({page:'stock-all',message:value,context:{part:selected}});};
 const drawerRef=useRef<HTMLElement>(null),opener=useRef<HTMLElement|null>(null),searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const search=(event:Event)=>{setFilters(f=>({...f,search:String((event as CustomEvent).detail||'')}));setPage(1);setChecked([]);};const shortcut=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();searchRef.current?.focus();}};window.addEventListener('stock-overview-search',search);window.addEventListener('keydown',shortcut);return()=>{window.removeEventListener('stock-overview-search',search);window.removeEventListener('keydown',shortcut);};},[]);
 useEffect(()=>{window.dispatchEvent(new CustomEvent("stock-overview-search-value",{detail:filters.search}));},[filters.search]);
 const query=stockFilterParams(filters).toString();
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{setLoading(true);setError('');fetch(`/api/stock-all?${query}&page=${page}&pageSize=${pageSize}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json() as Snapshot & {error?:string};if(!r.ok)throw new Error(d.error||'โหลด Stock ไม่สำเร็จ');setData(d);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},250);return()=>{clearTimeout(timer);controller.abort();};},[query,page,pageSize,refresh]);
 useEffect(()=>{if(!selected || !canDetails)return;const controller=new AbortController();const timer=setTimeout(()=>{setDetailLoading(true);setDetailError('');fetch(`/api/stock-all?part=${encodeURIComponent(selected)}&tab=${tab}&page=${detailPage}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json() as Detail & {error?:string};if(!r.ok)throw new Error(d.error||'โหลดรายละเอียดไม่สำเร็จ');setDetail(d);}).catch(e=>{if(e.name!=='AbortError')setDetailError(e.message);}).finally(()=>{if(!controller.signal.aborted)setDetailLoading(false);});},0);return()=>{clearTimeout(timer);controller.abort();};},[selected,tab,detailPage,canDetails,refresh]);
 useEffect(()=>{if(!selected)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';drawerRef.current?.focus();return()=>{document.body.style.overflow=old;opener.current?.focus();};},[selected]);
 const change=<K extends keyof Filters>(key:K,value:Filters[K])=>{setFilters(f=>({...f,[key]:value}));setPage(1);setChecked([]);};
 const clear=()=>{setFilters(EMPTY);setPage(1);setChecked([]);};
 const open=(row:StockOverviewRow,event:React.MouseEvent<HTMLButtonElement>)=>{opener.current=event.currentTarget;setSelected(row.materialCode);setTab('tag');setDetailPage(1);setDetail(null);};
 const activeCount=Object.entries(filters).filter(([key,value])=>key!=='search' && value && value!=='all').length;
 const pages=Math.max(1,Math.ceil(data.total/pageSize));const current=Math.min(page,pages);
 const pageButtons=[...new Set([1,...Array.from({length:5},(_,i)=>current-2+i).filter(n=>n>1&&n<pages),pages])].sort((a,b)=>a-b);
 async function exportExcel(selectedOnly=false){if(!canExport||exporting)return;setExporting(true);setError('');try{const response=await fetch(`/api/stock-all?${query}&export=1${selectedOnly?'&selected='+encodeURIComponent(JSON.stringify(checked)):''}`,{cache:'no-store'});const snapshot=await response.json() as Snapshot & {error?:string};if(!response.ok)throw new Error(snapshot.error||'ส่งออกไม่สำเร็จ');const xlsx=await import('xlsx');xlsx.writeFile(createOverviewWorkbook(xlsx,snapshot.rows,snapshot.loadedAt),`KIT_Stock_All_${new Date(snapshot.loadedAt).toISOString().replace(/[:.]/g,'-')}.xlsx`);}catch(e){setError(e instanceof Error?e.message:'ส่งออกไม่สำเร็จ');}finally{setExporting(false);}}
 function onDrawerKey(event:React.KeyboardEvent<HTMLElement>){if(event.key==='Escape'){setSelected('');return;}if(event.key!=='Tab')return;const items=drawerRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select,[tabindex="0"]');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===drawerRef.current)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
 return <div className="stock-all-page stock-overview">
  <section className="stock-overview-header"><div className="stock-overview-title"><span><OverviewIcon name="box"/></span><div><h2>Stock ทั้งหมด</h2><div className="stock-reference-breadcrumb">หน้าหลัก <OverviewIcon name="chevron"/> Stock ทั้งหมด</div><p>ดู Stock ทุก Part รวมยอด ดู Tag / Job และส่งออก Excel</p></div></div><div className="stock-overview-updated"><OverviewIcon name="calendar"/><span>ข้อมูลล่าสุด<br/><b>{timeLabel(data.loadedAt)}</b></span><button className="button secondary" disabled={loading} onClick={()=>setRefresh(n=>n+1)}><OverviewIcon name="refresh"/>{loading?'กำลังโหลด…':'รีเฟรชข้อมูล'}</button></div></section>
  <section className="stock-overview-kpis page-summary">{([{label:'Part ทั้งหมด',value:data.summary.partCount,unit:'รายการ',status:'all',icon:'box'},{label:'Stock พร้อมใช้',value:data.summary.availableQty,unit:'ชิ้น',status:'available',icon:'check'},{label:'จัดงานรอส่ง',value:data.summary.arrangedQty,unit:'ชิ้น',status:'arranged',icon:'box'},{label:'คงเหลือรวม',value:data.summary.totalQty,unit:'ชิ้น',status:'remaining',icon:'grid'}]).map((k,i)=><button key={k.label} className={`stock-overview-kpi kpi-${i}`} aria-pressed={filters.status===k.status} onClick={()=>k.status==='all'?clear():change('status',k.status)}><span><OverviewIcon name={k.icon}/></span><div><small>{k.label}</small><b>{fmt(k.value)}</b><small>{k.unit}</small></div><em><OverviewIcon name="chevron"/></em></button>)}</section>
  <section className="card stock-overview-filter-card"><div className="stock-overview-search"><label className="stock-reference-search-field"><OverviewIcon name="search"/><input ref={searchRef} type="search" value={filters.search} onChange={e=>change('search',e.target.value)} placeholder="ค้นหา Part No. / ชื่อชิ้นงาน / ลูกค้า / Job / Location" aria-label="ค้นหา Stock ทุก Part"/></label><button className="button secondary" aria-expanded={showFilters} onClick={()=>setShowFilters(v=>!v)}><OverviewIcon name="filter"/>ตัวกรอง <small>({activeCount})</small><OverviewIcon name="down"/></button>{canExport&&<button className="button primary" disabled={loading||exporting} onClick={()=>void exportExcel()}><OverviewIcon name="download"/>{exporting?'กำลังส่งออก…':'ส่งออก Excel'}</button>}</div>
  {showFilters&&<div className="stock-overview-filters"><label>สถานะ Stock<select value={filters.status} onChange={e=>change('status',e.target.value)}><option value="all">ทั้งหมด</option><option value="available">มี Stock พร้อมใช้</option><option value="zero">Stock = 0</option><option value="arranged">มีงานจัดรอส่ง</option><option value="remaining">มีคงเหลือรวม</option></select></label><label>ลูกค้า / Location<select value={filters.customer?'customer:'+filters.customer:filters.location?'location:'+filters.location:''} onChange={e=>{const [key,...value]=e.target.value.split(':');setFilters(f=>({...f,customer:key==='customer'?value.join(':'):'',location:key==='location'?value.join(':'):''}));setPage(1);}}><option value="">ทั้งหมด</option><optgroup label="ลูกค้า">{[...new Set(data.options.map(r=>r.customer).filter(Boolean))].sort().map(v=><option key={v} value={'customer:'+v}>{v}</option>)}</optgroup><optgroup label="Location">{[...new Set(data.options.map(r=>r.location).filter(Boolean))].sort().map(v=><option key={v} value={'location:'+v}>{v}</option>)}</optgroup></select></label><label>Job<input value={filters.job} onChange={e=>change('job',e.target.value)} placeholder="ค้นหา Job บางส่วน"/></label><label title="กลุ่มตามรหัส Part 4 ตัวแรก">กลุ่ม Part<select value={filters.partGroup} onChange={e=>change('partGroup',e.target.value)}><option value="">ทั้งหมด</option>{[...new Set(data.options.map(r=>r.partGroup))].sort().map(v=><option key={v}>{v}</option>)}</select></label><label className="stock-overview-toggle"><input role="switch" type="checkbox" checked={filters.availableOnly} onChange={e=>change('availableOnly',e.target.checked)}/>แสดงเฉพาะ Stock พร้อมใช้</label><button className="text-button" onClick={clear} disabled={!activeCount&&!filters.search}>ล้างตัวกรองทั้งหมด</button></div>}</section>
  {error&&<p role="alert" className="stock-overview-error">{error}</p>}
  <section className="card stock-overview-table-card" aria-busy={loading}>{checked.length>0&&<div className="stock-reference-selection"><span>เลือก {fmt(checked.length)} Part</span>{canExport&&<button className="text-button" disabled={exporting} onClick={()=>void exportExcel(true)}>ส่งออกเฉพาะที่เลือก</button>}<button className="text-button" onClick={()=>setChecked([])}>ล้างการเลือก</button></div>}<h3>รายการ Stock ทั้งหมด ({fmt(data.total)})</h3><div className="table-wrap mobile-table-wrap"><table className="mobile-card-table stock-overview-table"><thead><tr><th><label className="stock-reference-check"><input type="checkbox" aria-label="เลือก Part ทั้งหมดในหน้านี้" checked={data.rows.length>0&&data.rows.every(r=>checked.includes(r.materialCode))} onChange={e=>setChecked(e.target.checked?[...new Set([...checked,...data.rows.map(r=>r.materialCode)])]:checked.filter(code=>!data.rows.some(r=>r.materialCode===code)))}/></label>Part / ชื่อชิ้นงาน</th><th>ลูกค้า / Location</th><th>Stock พร้อมใช้<small>(ชิ้น)</small></th><th>จัดงานรอส่ง<small>(ชิ้น)</small></th><th>คงเหลือรวม<small>(ชิ้น)</small></th><th>จำนวน Tag</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.materialCode}><td data-label="Part / ชื่อชิ้นงาน"><div className="stock-overview-part"><label className="stock-reference-check"><input type="checkbox" aria-label={`เลือก ${row.materialCode}`} checked={checked.includes(row.materialCode)} onChange={e=>setChecked(e.target.checked?[...checked,row.materialCode]:checked.filter(code=>code!==row.materialCode))}/></label><Photo row={row}/><span><b>{row.materialCode}</b><small>{row.partName}</small></span></div></td><td data-label="ลูกค้า / Location">{row.customer||'—'}<small>{row.location||'—'}</small></td><td className="num qty-ready" data-label="Stock พร้อมใช้">{fmt(row.availableQty)}</td><td className="num qty-arranged" data-label="จัดงานรอส่ง">{fmt(row.arrangedQty)}</td><td className="num qty-total" data-label="คงเหลือรวม">{fmt(row.totalQty)}</td><td className="num" data-label="จำนวน Tag">{canDetails?<button className="text-button" aria-label={`ดู ${row.tagCount} Tag ของ ${row.materialCode}`} onClick={e=>open(row,e)}>{fmt(row.tagCount)}</button>:fmt(row.tagCount)}</td><td data-label="สถานะ"><Badge row={row}/></td><td data-label="จัดการ">{canDetails?<button className="tiny-button" onClick={e=>open(row,e)}>ดู Tag / Job <OverviewIcon name="chevron"/></button>:<span>—</span>}</td></tr>)}</tbody></table></div>{!data.rows.length&&<p className="stock-overview-empty">{loading?'กำลังโหลดข้อมูลจริง…':'ไม่พบ Part ตามตัวกรอง'}</p>}
  <footer className="stock-overview-pagination"><label>แสดง <select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1);}}>{[10,25,50,100].map(v=><option key={v}>{v}</option>)}</select> รายการต่อหน้า</label><nav aria-label="หน้ารายการ Stock"><button disabled={current<=1||loading} onClick={()=>setPage(current-1)}>‹</button>{pageButtons.map((n,i)=><span key={n}>{i>0&&n-pageButtons[i-1]>1&&<span>…</span>}<button className={n===current?'active':''} disabled={loading} aria-current={n===current?'page':undefined} onClick={()=>setPage(n)}>{n}</button></span>)}<button disabled={current>=pages||loading} onClick={()=>setPage(current+1)}>›</button></nav><span>แสดง {fmt(data.total?(current-1)*pageSize+1:0)}–{fmt(Math.min(current*pageSize,data.total))} จาก {fmt(data.total)} รายการ</span></footer></section>
  <p className="stock-all-note">คงเหลือรวม = Stock พร้อมใช้ + จัดงานรอส่ง · รวมทุก Part ใน Part Master แม้ไม่มี Tag · จำนวน Tag นับเฉพาะงานคงเหลือจริง</p>
  {selected&&canDetails&&<div className="stock-overview-backdrop" onClick={()=>setSelected('')}><aside ref={drawerRef} className="stock-overview-drawer" role="dialog" aria-modal="true" aria-label={`Tag / Job ${selected}`} tabIndex={-1} onKeyDown={onDrawerKey} onClick={e=>e.stopPropagation()}><header><h3>Tag / Job · {selected}</h3><button className="button secondary" onClick={()=>setSelected('')} aria-label="ปิดรายละเอียด">×</button></header>{detail&&<><div className="stock-overview-drawer-part"><Photo row={detail.part}/><div><b>{detail.part.materialCode}</b><p>{detail.part.partName}</p><small>{detail.part.customer} · {detail.part.location||'—'}</small><Badge row={detail.part}/></div></div><div className="stock-overview-detail-metrics">{[['Stock พร้อมใช้',detail.part.availableQty],['จัดงานรอส่ง',detail.part.arrangedQty],['คงเหลือรวม',detail.part.totalQty]].map(([label,value])=><div key={label}><small>{label}</small><b>{fmt(Number(value))}</b></div>)}</div></>}
  <div className="stock-overview-tabs" role="tablist" aria-label="รายละเอียด Part">{['tag','job','movement'].map(t=><button role="tab" aria-selected={tab===t} key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setDetailPage(1);}}>{t==='tag'?'Tag':t==='job'?'Job':'Movement'}</button>)}</div>{detailError&&<p role="alert">{detailError}</p>}{detailLoading?<p>กำลังโหลดรายละเอียด…</p>:<div role="tabpanel" className="table-wrap"><table className="stock-overview-detail-table"><thead><tr>{(tab==='tag'?['Tag / Job','คงเหลือ / พร้อมใช้ / จัดรอส่ง','ผลิตวันที่','สถานะ / Location']:tab==='job'?['Job No.','จำนวนรับเข้า','คงเหลือ','วันที่รับครั้งแรก']:['รายการ / Tag / Job','จำนวน','วันที่','ผู้ดำเนินการ']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{detail?.rows.map((r,i)=><tr key={r.id||r.jobNo||i}>{tab==='tag'?<><td><b>{r.tagId}</b><small>{r.jobNo}</small></td><td>{fmt(r.remainingQty||0)} / {fmt(r.availableQty||0)} / {fmt(r.arrangedQty||0)}</td><td>{dateLabel(r.productionDate||'')}</td><td>{r.status==='in_stock'?'รับเข้าแล้ว':r.status==='depleted'?'คงเหลือบางส่วน':r.status}<small>{r.location||'—'}</small></td></>:tab==='job'?<><td>{r.jobNo||'—'}</td><td>{fmt(r.receivedQty||0)}</td><td>{fmt(r.remainingQty||0)}</td><td>{timeLabel(r.receivedAt||'')}</td></>:<><td><b>{r.action}</b><small>{r.tagId} · {r.jobNo}</small></td><td>{fmt(r.qty||0)}</td><td>{timeLabel(r.occurredAt||'')}</td><td>{r.actor||'—'}</td></>}</tr>)}</tbody></table>{!detail?.rows.length&&<p>ไม่มีรายการในส่วนนี้</p>}</div>}
  <footer className="stock-overview-pagination"><button className="button secondary" disabled={detailPage<=1||detailLoading} onClick={()=>setDetailPage(p=>p-1)}>ก่อนหน้า</button><span>หน้า {detailPage} / {Math.max(1,Math.ceil((detail?.total||0)/25))} · {fmt(detail?.total||0)} รายการ</span><button className="button secondary" disabled={detailLoading||detailPage*25>=(detail?.total||0)} onClick={()=>setDetailPage(p=>p+1)}>ถัดไป</button></footer></aside></div>}
 </div>;
}
